---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: observability
  labels:
    grafana.internal/instance: grafana
spec:
  config:
    analytics:
      check_for_updates: "false"
      check_for_plugin_updates: "false"
      feedback_links_enabled: "false"
      reporting_enabled: "false"
    auth.basic:
      enabled: "true"
    auth.anonymous:
      enabled: "false"
    log:
      mode: console
    metrics:
      enabled: "true"
    news:
      news_feed_enabled: "false"
    plugins:
      plugin_admin_enabled: "false"
    server:
      enable_gzip: "true"
      root_url: http://localhost:30300
  service:
    spec:
      type: NodePort
      ports:
        - name: grafana-http
          port: 3000
          targetPort: 3000
          nodePort: 30300
          protocol: TCP
  deployment:
    spec:
      strategy:
        type: Recreate
      template:
        spec:
          containers:
            - name: grafana
              resources:
                requests: {cpu: 25m, memory: 128Mi}
                limits: {cpu: 500m, memory: 384Mi}
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop: ["ALL"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 472
            runAsGroup: 472
            fsGroup: 472
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault
  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: local-path
  disableDefaultSecurityContext: All
