---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flux-components
  namespace: observability
  labels:
    app.kubernetes.io/part-of: flux
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values:
          - helm-controller
          - source-controller
          - kustomize-controller
          - notification-controller
  podMetricsEndpoints:
    - port: http-prom
      honorLabels: true
      interval: 1m
      scrapeTimeout: 30s
